Initial build
mslmio/sdk-swift pull request #1
Opened 2023-12-22 23:35 UTC by muhammadahmadmslm

- [x] Support SPM (Swift Package Manager)
- [x] SingleVerify
- [x] OTP Send
- [x] OTP Verify
- [x] Test Cases
- [x] readme.md
- [x] Mslm class to access both(Single Verify, OTP)
- [x] swift lint
- [x] bash file added
- [x] swift fmd

2023-12-24 09:13 UTC, UmanShahzad requested changes
- You need to remember we are aiming to have 100s or more APIs within each SDK. You need to structure the hierarchy, naming and grouping such that it is scalable.
- @Usama109c can you also please review?

2023-12-24 09:13 UTC, UmanShahzad commented on README.md
> +
Please mention how to initialize sub-components of the library as well, e.g. importing **just email verify** or **just OTP** and then using just that client and not the overall Mslm one.

2023-12-24 09:13 UTC, UmanShahzad commented on README.md
> +### 3. OTP Service Usage
What is the standard way to deploy and publish Swift code documentation? I'm assuming it's certainly **not** a README.md file like we've done below, right?

We're going to have hundreds of APIs. Need the 'official' and scalable method of documenting API functions and making them available to all.

2023-12-24 09:13 UTC, UmanShahzad commented on README.md
> +
Remove 1 trailing newline, there's an extra beyond what we need

2023-12-24 09:13 UTC, UmanShahzad commented on README.md
> +This section provides a guide on how to use the Swift API Client for OTP and Email Verification Services in your project.
```suggestion
Let's go through how to start using the Mslm Swift SDK with sample code.
```

2023-12-24 09:13 UTC, UmanShahzad commented on README.md
> +The Mslm Swift library can be authenticated with your Mslm API access token, which is passed with this key `MslmApiKey` in `info.plist` file. Your Mslm access token can be found in the account sectio
Please reword things to not say 'library' but just 'Mslm Swift SDK'

2023-12-24 09:13 UTC, UmanShahzad commented on README.md
> +#### Swift Package Manager
Recall the feedback I gave about how to properly space headers in README files. The spacing here is severely messed up

2023-12-24 09:13 UTC, UmanShahzad commented on README.md
> +## Table of Contents
Please delete as it's unnecesary; Github already generates a ToC within the UI

2023-12-24 09:13 UTC, UmanShahzad commented on README.md
> +Swift API Client for OTP and Email Verification Services: A versatile Swift library designed for easy integration with OTP (One-Time Password) and Email Verification services. This library provides s
See github.com/mslmio/sdk-go for an idea of the 'right' way to show our start README and other details.

2023-12-24 09:13 UTC, UmanShahzad commented on README.md
> +## Overview
Empty section

2023-12-24 09:13 UTC, UmanShahzad commented on Sources/Constant/Constant.swift
> +	static let OTP_VERIFY_ENDPOINT = "/api/otp/v1/token_verify"
Please define the specific URL endpoints within the related endpoint functionality/code, not globally here.

We're going to have 100s of APIs and need a scalable method.

2023-12-24 09:13 UTC, UmanShahzad commented on Sources/Constant/Constant.swift
> +	static var APP_VERSION: String {
Why do we need it?

2023-12-24 09:13 UTC, UmanShahzad commented on Sources/Constant/Constant.swift
> +	static var APP_NAME: String {
Why do we need it?

2023-12-24 09:13 UTC, UmanShahzad commented on Sources/SingleVerify/SingleVerify.swift
> +	public func singleVarify(_ email: String, completion: @escaping ((Result<SingleVerifyResp, Error>) -> Void)) {
Typo

2023-12-24 09:13 UTC, UmanShahzad commented on Sources/Utilits/Extensions/Bundle + Extension.swift
Folder name for utilities is mis-spelled.

`Utilities`

2023-12-24 09:13 UTC, UmanShahzad commented on Sources/Mslm/Mslm.swift
> +	public let emailVerify: SingleVerify
Why are we calling it the 'SingleVerify' service when it's really the 'EmailVerify' service?

2023-12-24 09:13 UTC, UmanShahzad commented on Sources/Mslm/Mslm.swift
> +	public let otp: OTPService
Can we remove Service from the name of these

2023-12-24 09:13 UTC, UmanShahzad commented on Sources/Models/SingleVerifyResp/SingleVerifyResp.swift
The folder groupings for these models seem too specific. Can we have a EmailVerify models folder and then this resp inside of it? Take note in case we need a BulkVerify API.

2023-12-24 09:13 UTC, UmanShahzad commented on Sources/Service/Service + Endpoint.swift
> +		case .otpVerify(let params, let method):
We can't be doing things like this, hard-coding all of the individual URLs within a generic service functionality. No way. See the Golang one

2023-12-24 09:13 UTC, UmanShahzad commented on Sources/Service/Service + Router.swift
> +extension Service {
Same

2023-12-24 09:41 UTC, Usama109c commented on Sources/SingleVerify/SingleVerify.swift
> +	public func singleVarify(_ email: String, completion: @escaping ((Result<SingleVerifyResp, Error>) -> Void)) {
Also why the SingleVerifyResp is not optional?

2023-12-24 09:41 UTC, Usama109c commented on Sources/Service/Service + Endpoint.swift
> +		// Construct the URL for OTP verification request
Can we move this implementation into single function and call it here and the above function. Because almost all functionality is same just some params are being updated.

2023-12-24 09:41 UTC, Usama109c commented on Sources/Models/SingleVerifyResp/SingleVerifyResp.swift
> +	public let email: String
Why the response parameters are not optional? Are we really sure that all of them will get value?

2024-01-02 00:47 UTC, muhammadahmadmslm commented on README.md
> +
Brother it is described a little down in the file

2024-01-03 05:26 UTC, UmanShahzad approved these changes

2024-01-03 05:26 UTC, UmanShahzad commented on README.md
> +The official Go SDK for Mslm APIs.
Go? Bro

2024-01-03 11:13 UTC, merged